server.port=${POSITION_SERVICE_PORT:18090}
server.forward-headers-strategy=framework

spring.datasource.url=jdbc:h2:tcp://${DATABASE_TCP_HOST:localhost}:${DATABASE_TCP_PORT:18082}/${DATABASE_NAME:traderx};CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DATABASE_DBUSER:sa}
spring.datasource.password=${DATABASE_DBPASS:sa}
spring.threads.virtual.enabled=true

server.max-http-request-header-size=1000000

traderx.cache.enabled=${CACHE_ENABLED:false}
traderx.cache.ttl=${CACHE_TTL:30s}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}
